/* Mon Français 단어 데이터
 * ⚠️ 진행 기록이 배열 인덱스 기준 — 기존 단어의 순서 변경·삭제 금지. 새 단어는 반드시 배열 끝에 추가.
 * 형식: { f:프랑스어, p:품사, ko:한국어 뜻, en:영어 뜻, ex:예문, exko:예문 번역, lv:1~3 (없으면 1=기초) }
 */
const WORDS = [
{f:"être",p:"동사",ko:"~이다, 있다",en:"to be",ex:"Je suis coréen.",exko:"저는 한국인이에요."},
{f:"avoir",p:"동사",ko:"가지다",en:"to have",ex:"J'ai une question.",exko:"질문이 하나 있어요."},
{f:"faire",p:"동사",ko:"하다, 만들다",en:"to do, to make",ex:"Qu'est-ce que tu fais ce week-end ?",exko:"이번 주말에 뭐 해?"},
{f:"aller",p:"동사",ko:"가다",en:"to go",ex:"Je vais au bureau.",exko:"저는 사무실에 가요."},
{f:"pouvoir",p:"동사",ko:"~할 수 있다",en:"can, to be able to",ex:"Tu peux m'aider ?",exko:"나 좀 도와줄 수 있어?"},
{f:"vouloir",p:"동사",ko:"원하다",en:"to want",ex:"Je veux apprendre le français.",exko:"저는 프랑스어를 배우고 싶어요."},
{f:"devoir",p:"동사",ko:"~해야 하다",en:"must, to have to",ex:"Je dois partir à cinq heures.",exko:"저는 5시에 가야 해요."},
{f:"savoir",p:"동사",ko:"알다 (지식)",en:"to know (facts)",ex:"Je ne sais pas.",exko:"모르겠어요."},
{f:"venir",p:"동사",ko:"오다",en:"to come",ex:"Tu viens avec nous ?",exko:"우리랑 같이 갈래?"},
{f:"voir",p:"동사",ko:"보다",en:"to see",ex:"On se voit demain ?",exko:"내일 볼까?"},
{f:"prendre",p:"동사",ko:"잡다, 타다, 먹다",en:"to take",ex:"Je prends un café.",exko:"커피 한 잔 마실게요."},
{f:"parler",p:"동사",ko:"말하다",en:"to speak",ex:"Je parle un peu français.",exko:"저는 프랑스어를 조금 해요."},
{f:"aimer",p:"동사",ko:"좋아하다, 사랑하다",en:"to like, to love",ex:"J'aime beaucoup ce restaurant.",exko:"저는 이 식당을 정말 좋아해요."},
{f:"manger",p:"동사",ko:"먹다",en:"to eat",ex:"On mange ensemble à midi ?",exko:"점심에 같이 먹을까?"},
{f:"donner",p:"동사",ko:"주다",en:"to give",ex:"Tu peux me donner ton avis ?",exko:"네 의견 좀 줄 수 있어?"},
{f:"trouver",p:"동사",ko:"찾다, ~라고 생각하다",en:"to find",ex:"Je trouve ça intéressant.",exko:"저는 그게 흥미롭다고 생각해요."},
{f:"penser",p:"동사",ko:"생각하다",en:"to think",ex:"Qu'est-ce que tu en penses ?",exko:"그거에 대해 어떻게 생각해?"},
{f:"travailler",p:"동사",ko:"일하다",en:"to work",ex:"Je travaille dans une entreprise française.",exko:"저는 프랑스 회사에서 일해요."},
{f:"comprendre",p:"동사",ko:"이해하다",en:"to understand",ex:"Désolé, je n'ai pas compris.",exko:"죄송해요, 이해 못 했어요."},
{f:"attendre",p:"동사",ko:"기다리다",en:"to wait",ex:"Attends une seconde !",exko:"잠깐만 기다려!"},
{f:"demander",p:"동사",ko:"묻다, 요청하다",en:"to ask",ex:"Je peux te demander quelque chose ?",exko:"뭐 하나 물어봐도 돼?"},
{f:"partir",p:"동사",ko:"떠나다, 출발하다",en:"to leave",ex:"Le train part à huit heures.",exko:"기차는 8시에 출발해요."},
{f:"arriver",p:"동사",ko:"도착하다",en:"to arrive",ex:"J'arrive dans dix minutes.",exko:"10분 뒤에 도착해요."},
{f:"rester",p:"동사",ko:"머무르다, 남다",en:"to stay",ex:"Je reste à la maison ce soir.",exko:"오늘 저녁엔 집에 있을 거예요."},
{f:"passer",p:"동사",ko:"지나가다, (시간을) 보내다",en:"to pass, to spend",ex:"J'ai passé un bon week-end.",exko:"좋은 주말을 보냈어요."},
{f:"mettre",p:"동사",ko:"놓다, 넣다, 입다",en:"to put",ex:"Je mets mon manteau.",exko:"코트를 입을게요."},
{f:"dire",p:"동사",ko:"말하다",en:"to say",ex:"Comment on dit ça en français ?",exko:"이거 프랑스어로 어떻게 말해요?"},
{f:"boire",p:"동사",ko:"마시다",en:"to drink",ex:"Tu veux boire quelque chose ?",exko:"뭐 마실래?"},
{f:"acheter",p:"동사",ko:"사다",en:"to buy",ex:"J'ai acheté du pain à la boulangerie.",exko:"빵집에서 빵을 샀어요."},
{f:"payer",p:"동사",ko:"지불하다",en:"to pay",ex:"Je peux payer par carte ?",exko:"카드로 결제할 수 있나요?"},
{f:"habiter",p:"동사",ko:"살다, 거주하다",en:"to live",ex:"J'habite à Paris depuis un an.",exko:"파리에 산 지 1년 됐어요."},
{f:"connaître",p:"동사",ko:"알다 (사람·장소)",en:"to know (people, places)",ex:"Tu connais ce quartier ?",exko:"이 동네 알아?"},
{f:"commencer",p:"동사",ko:"시작하다",en:"to start",ex:"La réunion commence à dix heures.",exko:"회의는 10시에 시작해요."},
{f:"finir",p:"동사",ko:"끝내다",en:"to finish",ex:"Je finis le travail à six heures.",exko:"저는 6시에 일이 끝나요."},
{f:"appeler",p:"동사",ko:"부르다, 전화하다",en:"to call",ex:"Je m'appelle Jaehwan.",exko:"제 이름은 재환이에요."},
{f:"écouter",p:"동사",ko:"듣다",en:"to listen",ex:"J'écoute un podcast en français.",exko:"프랑스어 팟캐스트를 들어요."},
{f:"regarder",p:"동사",ko:"보다, 쳐다보다",en:"to watch, to look",ex:"Regarde ça, c'est drôle !",exko:"이거 봐, 웃겨!"},
{f:"apprendre",p:"동사",ko:"배우다",en:"to learn",ex:"J'apprends dix mots par jour.",exko:"저는 하루에 단어 10개를 배워요."},
{f:"essayer",p:"동사",ko:"시도하다, 노력하다",en:"to try",ex:"J'essaie de parler français au travail.",exko:"회사에서 프랑스어로 말하려고 노력해요."},
{f:"aider",p:"동사",ko:"돕다",en:"to help",ex:"Merci de m'avoir aidé !",exko:"도와줘서 고마워!"},
{f:"bonjour",p:"인사",ko:"안녕하세요 (낮)",en:"hello, good morning",ex:"Bonjour, ça va ?",exko:"안녕하세요, 잘 지내요?"},
{f:"bonsoir",p:"인사",ko:"안녕하세요 (저녁)",en:"good evening",ex:"Bonsoir tout le monde !",exko:"모두들 좋은 저녁이에요!"},
{f:"merci",p:"인사",ko:"고맙습니다",en:"thank you",ex:"Merci beaucoup pour votre aide.",exko:"도와주셔서 정말 감사합니다."},
{f:"s'il vous plaît",p:"인사",ko:"부탁합니다 (존댓말)",en:"please (formal)",ex:"Un croissant, s'il vous plaît.",exko:"크루아상 하나 주세요."},
{f:"pardon",p:"인사",ko:"실례합니다, 죄송해요",en:"excuse me, sorry",ex:"Pardon, je n'ai pas entendu.",exko:"죄송해요, 못 들었어요."},
{f:"désolé",p:"형용사",ko:"미안한",en:"sorry",ex:"Désolé pour le retard.",exko:"늦어서 죄송해요."},
{f:"oui",p:"부사",ko:"네",en:"yes",ex:"Oui, bien sûr !",exko:"네, 물론이죠!"},
{f:"non",p:"부사",ko:"아니요",en:"no",ex:"Non, merci.",exko:"아니요, 괜찮아요."},
{f:"peut-être",p:"부사",ko:"아마도",en:"maybe",ex:"Peut-être demain, je ne suis pas sûr.",exko:"아마 내일이요, 확실하지 않아요."},
{f:"aujourd'hui",p:"부사",ko:"오늘",en:"today",ex:"Aujourd'hui, il fait beau.",exko:"오늘은 날씨가 좋네요."},
{f:"demain",p:"부사",ko:"내일",en:"tomorrow",ex:"À demain !",exko:"내일 봐요!"},
{f:"hier",p:"부사",ko:"어제",en:"yesterday",ex:"Hier, j'ai travaillé tard.",exko:"어제 늦게까지 일했어요."},
{f:"maintenant",p:"부사",ko:"지금",en:"now",ex:"On peut commencer maintenant.",exko:"지금 시작해도 돼요."},
{f:"toujours",p:"부사",ko:"항상, 여전히",en:"always, still",ex:"Il est toujours en retard.",exko:"그는 항상 늦어요."},
{f:"souvent",p:"부사",ko:"자주",en:"often",ex:"Je viens souvent ici.",exko:"저 여기 자주 와요."},
{f:"jamais",p:"부사",ko:"결코 ~않다",en:"never",ex:"Je ne bois jamais de café le soir.",exko:"저는 저녁에 커피를 절대 안 마셔요."},
{f:"beaucoup",p:"부사",ko:"많이",en:"a lot",ex:"Merci beaucoup !",exko:"정말 감사해요!"},
{f:"un peu",p:"부사",ko:"조금",en:"a little",ex:"Je parle un peu français.",exko:"프랑스어를 조금 해요."},
{f:"très",p:"부사",ko:"매우",en:"very",ex:"C'est très bon !",exko:"이거 정말 맛있어요!"},
{f:"trop",p:"부사",ko:"너무",en:"too much",ex:"C'est trop cher.",exko:"너무 비싸요."},
{f:"vraiment",p:"부사",ko:"정말로",en:"really",ex:"C'est vraiment gentil.",exko:"정말 친절하시네요."},
{f:"aussi",p:"부사",ko:"~도, 또한",en:"also, too",ex:"Moi aussi !",exko:"나도!"},
{f:"encore",p:"부사",ko:"아직, 또",en:"still, again",ex:"Encore une fois, s'il vous plaît.",exko:"한 번 더 부탁드려요."},
{f:"déjà",p:"부사",ko:"이미, 벌써",en:"already",ex:"Tu as déjà fini ?",exko:"벌써 끝났어?"},
{f:"ici",p:"부사",ko:"여기",en:"here",ex:"C'est ici.",exko:"여기예요."},
{f:"là-bas",p:"부사",ko:"저기",en:"over there",ex:"Le bureau est là-bas.",exko:"사무실은 저기예요."},
{f:"bien",p:"부사",ko:"잘, 좋게",en:"well",ex:"Très bien, merci.",exko:"아주 좋아요, 고마워요."},
{f:"mal",p:"부사",ko:"나쁘게, 잘못",en:"badly",ex:"J'ai mal dormi.",exko:"잠을 잘 못 잤어요."},
{f:"vite",p:"부사",ko:"빨리",en:"quickly",ex:"Tu parles trop vite !",exko:"너무 빨리 말해!"},
{f:"lentement",p:"부사",ko:"천천히",en:"slowly",ex:"Vous pouvez parler plus lentement ?",exko:"좀 더 천천히 말씀해주시겠어요?"},
{f:"le travail",p:"명사",ko:"일, 직장",en:"work, job",ex:"Le travail, ça va ?",exko:"일은 잘돼가?"},
{f:"la réunion",p:"명사",ko:"회의",en:"meeting",ex:"J'ai une réunion à quatorze heures.",exko:"2시에 회의가 있어요."},
{f:"le bureau",p:"명사",ko:"사무실, 책상",en:"office, desk",ex:"Je suis au bureau.",exko:"저는 사무실에 있어요."},
{f:"l'entreprise",p:"명사",ko:"회사",en:"company",ex:"C'est une grande entreprise.",exko:"큰 회사예요."},
{f:"le collègue",p:"명사",ko:"동료",en:"colleague",ex:"Mes collègues sont sympas.",exko:"제 동료들은 좋은 사람들이에요."},
{f:"le projet",p:"명사",ko:"프로젝트",en:"project",ex:"Le projet avance bien.",exko:"프로젝트가 잘 진행되고 있어요."},
{f:"la question",p:"명사",ko:"질문",en:"question",ex:"J'ai une petite question.",exko:"작은 질문이 하나 있어요."},
{f:"la réponse",p:"명사",ko:"대답",en:"answer",ex:"Je n'ai pas encore de réponse.",exko:"아직 답을 못 받았어요."},
{f:"le temps",p:"명사",ko:"시간, 날씨",en:"time, weather",ex:"Je n'ai pas le temps.",exko:"시간이 없어요."},
{f:"le jour",p:"명사",ko:"날, 하루",en:"day",ex:"Quel jour sommes-nous ?",exko:"오늘 무슨 요일이죠?"},
{f:"la semaine",p:"명사",ko:"주, 일주일",en:"week",ex:"La semaine prochaine, je suis en vacances.",exko:"다음 주에 휴가예요."},
{f:"le mois",p:"명사",ko:"달, 월",en:"month",ex:"Je suis arrivé il y a six mois.",exko:"6개월 전에 왔어요."},
{f:"l'année",p:"명사",ko:"해, 년",en:"year",ex:"Bonne année !",exko:"새해 복 많이 받으세요!"},
{f:"le matin",p:"명사",ko:"아침",en:"morning",ex:"Je bois un café le matin.",exko:"아침에 커피를 마셔요."},
{f:"le soir",p:"명사",ko:"저녁",en:"evening",ex:"Qu'est-ce que tu fais ce soir ?",exko:"오늘 저녁에 뭐 해?"},
{f:"le week-end",p:"명사",ko:"주말",en:"weekend",ex:"Bon week-end !",exko:"좋은 주말 보내!"},
{f:"les vacances",p:"명사",ko:"휴가, 방학",en:"vacation",ex:"Tu pars où en vacances ?",exko:"휴가 때 어디 가?"},
{f:"la maison",p:"명사",ko:"집",en:"house, home",ex:"Je rentre à la maison.",exko:"집에 가요."},
{f:"la ville",p:"명사",ko:"도시",en:"city",ex:"J'adore cette ville.",exko:"이 도시가 정말 좋아요."},
{f:"la rue",p:"명사",ko:"거리, 길",en:"street",ex:"C'est dans quelle rue ?",exko:"어느 거리에 있어요?"},
{f:"le magasin",p:"명사",ko:"가게",en:"store",ex:"Le magasin ferme à vingt heures.",exko:"가게는 8시에 닫아요."},
{f:"le restaurant",p:"명사",ko:"식당",en:"restaurant",ex:"On va au restaurant ce soir ?",exko:"오늘 저녁에 식당 갈까?"},
{f:"l'eau",p:"명사",ko:"물",en:"water",ex:"Une carafe d'eau, s'il vous plaît.",exko:"물 한 병 주세요."},
{f:"le pain",p:"명사",ko:"빵",en:"bread",ex:"Une baguette, s'il vous plaît.",exko:"바게트 하나 주세요."},
{f:"le déjeuner",p:"명사",ko:"점심",en:"lunch",ex:"On déjeune ensemble ?",exko:"점심 같이 먹을까요?"},
{f:"le dîner",p:"명사",ko:"저녁 식사",en:"dinner",ex:"Le dîner est prêt.",exko:"저녁 준비됐어요."},
{f:"l'argent",p:"명사",ko:"돈",en:"money",ex:"Ça coûte combien ?",exko:"얼마예요?"},
{f:"la chose",p:"명사",ko:"것, 물건",en:"thing",ex:"J'ai plein de choses à faire.",exko:"할 일이 많아요."},
{f:"le problème",p:"명사",ko:"문제",en:"problem",ex:"Pas de problème !",exko:"문제없어요!"},
{f:"l'ami",p:"명사",ko:"친구",en:"friend",ex:"C'est un bon ami.",exko:"좋은 친구예요."},
{f:"la famille",p:"명사",ko:"가족",en:"family",ex:"Ma famille habite en Corée.",exko:"제 가족은 한국에 살아요."},
{f:"bon",p:"형용사",ko:"좋은, 맛있는",en:"good",ex:"C'est très bon !",exko:"정말 맛있어요!"},
{f:"mauvais",p:"형용사",ko:"나쁜",en:"bad",ex:"C'est une mauvaise idée.",exko:"그건 나쁜 생각이에요."},
{f:"grand",p:"형용사",ko:"큰, 키 큰",en:"big, tall",ex:"C'est une grande ville.",exko:"큰 도시예요."},
{f:"petit",p:"형용사",ko:"작은",en:"small",ex:"Un petit café, s'il vous plaît.",exko:"작은 커피 하나 주세요."},
{f:"nouveau",p:"형용사",ko:"새로운",en:"new",ex:"J'ai un nouveau travail.",exko:"새 직장을 구했어요."},
{f:"important",p:"형용사",ko:"중요한",en:"important",ex:"C'est très important pour moi.",exko:"저한테 아주 중요해요."},
{f:"difficile",p:"형용사",ko:"어려운",en:"difficult",ex:"Le français, c'est difficile !",exko:"프랑스어는 어려워요!"},
{f:"facile",p:"형용사",ko:"쉬운",en:"easy",ex:"C'est facile à comprendre.",exko:"이해하기 쉬워요."},
{f:"content",p:"형용사",ko:"기쁜, 만족한",en:"happy, glad",ex:"Je suis content de te voir.",exko:"만나서 기뻐."},
{f:"fatigué",p:"형용사",ko:"피곤한",en:"tired",ex:"Je suis un peu fatigué aujourd'hui.",exko:"오늘 좀 피곤해요."},
{f:"intéressant",p:"형용사",ko:"흥미로운",en:"interesting",ex:"C'est un sujet intéressant.",exko:"흥미로운 주제네요."},
{f:"cher",p:"형용사",ko:"비싼",en:"expensive",ex:"C'est un peu cher.",exko:"좀 비싸네요."},
{f:"prêt",p:"형용사",ko:"준비된",en:"ready",ex:"Tu es prêt ?",exko:"준비됐어?"},
{f:"mais",p:"접속사",ko:"하지만",en:"but",ex:"C'est bien, mais c'est cher.",exko:"좋긴 한데 비싸요."},
{f:"parce que",p:"접속사",ko:"왜냐하면",en:"because",ex:"Je suis fatigué parce que j'ai mal dormi.",exko:"잠을 잘 못 자서 피곤해요."},
{f:"donc",p:"접속사",ko:"그래서",en:"so, therefore",ex:"Il pleut, donc je reste chez moi.",exko:"비가 와서 집에 있어요."},
{f:"quand",p:"접속사",ko:"언제, ~할 때",en:"when",ex:"Tu arrives quand ?",exko:"언제 도착해?"},
{f:"si",p:"접속사",ko:"만약 ~라면",en:"if",ex:"Si tu veux, on y va ensemble.",exko:"원하면 같이 가자."},
{f:"avec",p:"전치사",ko:"~와 함께",en:"with",ex:"Je viens avec toi.",exko:"너랑 같이 갈게."},
{f:"sans",p:"전치사",ko:"~없이",en:"without",ex:"Un café sans sucre, s'il vous plaît.",exko:"설탕 없이 커피 주세요."},
{f:"pour",p:"전치사",ko:"~를 위해",en:"for",ex:"C'est pour moi ?",exko:"이거 저 주는 거예요?"},
{f:"avant",p:"전치사",ko:"~전에",en:"before",ex:"Appelle-moi avant midi.",exko:"정오 전에 전화해줘."},
{f:"après",p:"전치사",ko:"~후에",en:"after",ex:"On se voit après le travail ?",exko:"퇴근 후에 볼까?"},
{f:"pendant",p:"전치사",ko:"~동안",en:"during",ex:"Pendant la réunion, prends des notes.",exko:"회의 동안 메모해."},
{f:"depuis",p:"전치사",ko:"~이후로, ~한 지",en:"since, for",ex:"J'habite ici depuis un an.",exko:"여기 산 지 1년 됐어요."},
{f:"comment",p:"의문사",ko:"어떻게",en:"how",ex:"Comment ça marche ?",exko:"이거 어떻게 작동해요?"},
{f:"pourquoi",p:"의문사",ko:"왜",en:"why",ex:"Pourquoi pas ?",exko:"왜 안 되겠어? (좋지!)"},
{f:"où",p:"의문사",ko:"어디",en:"where",ex:"Tu habites où ?",exko:"어디 살아?"},
{f:"qui",p:"의문사",ko:"누구",en:"who",ex:"C'est qui ?",exko:"저 사람 누구야?"},
{f:"combien",p:"의문사",ko:"얼마나, 몇",en:"how much, how many",ex:"Ça coûte combien ?",exko:"얼마예요?"},
{f:"quel",p:"의문사",ko:"어떤, 무슨",en:"which, what",ex:"Quelle heure est-il ?",exko:"몇 시예요?"},
{f:"quelque chose",p:"대명사",ko:"무언가",en:"something",ex:"Tu veux manger quelque chose ?",exko:"뭐 좀 먹을래?"},
{f:"tout",p:"대명사",ko:"모든 것, 전부",en:"everything, all",ex:"Tout va bien ?",exko:"다 괜찮아?"},
{f:"rien",p:"대명사",ko:"아무것도 (~않다)",en:"nothing",ex:"Ce n'est rien.",exko:"아무것도 아니에요."},
{f:"l'heure",p:"명사",ko:"시간, 시각",en:"hour, time",ex:"Il est quelle heure ?",exko:"지금 몇 시예요?"},
{f:"la fois",p:"명사",ko:"번, 회",en:"time (occurrence)",ex:"C'est la première fois.",exko:"처음이에요."},
{f:"le monde",p:"명사",ko:"세상, 사람들",en:"world, people",ex:"Il y a beaucoup de monde ici.",exko:"여기 사람이 많네요."},
{f:"la vie",p:"명사",ko:"삶, 인생",en:"life",ex:"C'est la vie !",exko:"그게 인생이지!"},
{f:"l'idée",p:"명사",ko:"생각, 아이디어",en:"idea",ex:"Bonne idée !",exko:"좋은 생각이야!"},
{f:"la santé",p:"명사",ko:"건강",en:"health",ex:"Santé !",exko:"건배!"},
{f:"le rendez-vous",p:"명사",ko:"약속, 예약",en:"appointment",ex:"J'ai un rendez-vous chez le médecin.",exko:"병원 예약이 있어요."},
{f:"le mail",p:"명사",ko:"이메일",en:"email",ex:"Je t'envoie un mail cet après-midi.",exko:"오후에 메일 보낼게."},
{f:"le dossier",p:"명사",ko:"서류, 파일",en:"file, folder",ex:"Tu as vu le dossier client ?",exko:"고객 파일 봤어?"},
{f:"la pause",p:"명사",ko:"휴식",en:"break",ex:"On fait une pause café ?",exko:"커피 마시며 쉴까?"},
{f:"envoyer",p:"동사",ko:"보내다",en:"to send",ex:"Je t'envoie le document.",exko:"문서 보내줄게."},
{f:"recevoir",p:"동사",ko:"받다",en:"to receive",ex:"J'ai bien reçu ton message.",exko:"네 메시지 잘 받았어."},
{f:"choisir",p:"동사",ko:"선택하다",en:"to choose",ex:"Vous avez choisi ?",exko:"결정하셨어요? (주문)"},
{f:"expliquer",p:"동사",ko:"설명하다",en:"to explain",ex:"Tu peux m'expliquer ?",exko:"설명해줄 수 있어?"},
{f:"répondre",p:"동사",ko:"대답하다",en:"to answer",ex:"Je réponds à ton mail ce soir.",exko:"오늘 저녁에 메일 답장할게."},
{f:"oublier",p:"동사",ko:"잊다",en:"to forget",ex:"J'ai oublié mon parapluie.",exko:"우산을 깜빡했어요."},
{f:"se souvenir",p:"동사",ko:"기억하다",en:"to remember",ex:"Tu te souviens de lui ?",exko:"그 사람 기억나?"},
{f:"changer",p:"동사",ko:"바꾸다",en:"to change",ex:"On peut changer la date ?",exko:"날짜를 바꿀 수 있을까요?"},
{f:"ouvrir",p:"동사",ko:"열다",en:"to open",ex:"Le magasin ouvre à neuf heures.",exko:"가게는 9시에 열어요."},
{f:"fermer",p:"동사",ko:"닫다",en:"to close",ex:"Tu peux fermer la fenêtre ?",exko:"창문 좀 닫아줄래?"},
{f:"perdre",p:"동사",ko:"잃다, 지다",en:"to lose",ex:"J'ai perdu mes clés.",exko:"열쇠를 잃어버렸어요."},
{f:"gagner",p:"동사",ko:"이기다, 벌다",en:"to win, to earn",ex:"On a gagné le match !",exko:"우리가 경기에서 이겼어!"},
{f:"lire",p:"동사",ko:"읽다",en:"to read",ex:"Je lis un livre en français.",exko:"프랑스어 책을 읽고 있어요."},
{f:"écrire",p:"동사",ko:"쓰다",en:"to write",ex:"Écris-moi quand tu arrives.",exko:"도착하면 연락해."},
{f:"dormir",p:"동사",ko:"자다",en:"to sleep",ex:"J'ai besoin de dormir.",exko:"자야 해요."},
{f:"se lever",p:"동사",ko:"일어나다",en:"to get up",ex:"Je me lève à sept heures.",exko:"저는 7시에 일어나요."},
{f:"rentrer",p:"동사",ko:"돌아가다, 귀가하다",en:"to go home",ex:"Je rentre tard ce soir.",exko:"오늘 저녁 늦게 들어가요."},
{f:"visiter",p:"동사",ko:"방문하다, 구경하다",en:"to visit",ex:"On a visité le Louvre.",exko:"루브르를 구경했어요."},
{f:"marcher",p:"동사",ko:"걷다, 작동하다",en:"to walk, to work (function)",ex:"Ça marche !",exko:"좋아, 그렇게 하자! (작동해요)"},
{f:"préférer",p:"동사",ko:"선호하다",en:"to prefer",ex:"Je préfère le thé au café.",exko:"커피보다 차를 더 좋아해요."},
{f:"avoir besoin de",p:"표현",ko:"~이 필요하다",en:"to need",ex:"J'ai besoin d'aide.",exko:"도움이 필요해요."},
{f:"avoir envie de",p:"표현",ko:"~하고 싶다",en:"to feel like",ex:"J'ai envie d'une glace.",exko:"아이스크림이 먹고 싶어요."},
{f:"il y a",p:"표현",ko:"~이 있다",en:"there is, there are",ex:"Il y a un problème.",exko:"문제가 있어요."},
{f:"il faut",p:"표현",ko:"~해야 한다",en:"one must, it is necessary",ex:"Il faut réserver à l'avance.",exko:"미리 예약해야 해요."},
{f:"ça va",p:"표현",ko:"잘 지내요 / 괜찮아요",en:"it's fine, how are you",ex:"Ça va, et toi ?",exko:"잘 지내, 너는?"},
{f:"d'accord",p:"표현",ko:"알겠어요, 동의해요",en:"okay, agreed",ex:"D'accord, on fait comme ça.",exko:"좋아요, 그렇게 해요."},
{f:"bien sûr",p:"표현",ko:"물론이죠",en:"of course",ex:"Bien sûr, pas de souci !",exko:"물론이죠, 걱정 마세요!"},
{f:"à bientôt",p:"표현",ko:"곧 봐요",en:"see you soon",ex:"Merci, à bientôt !",exko:"고마워요, 곧 봐요!"},
{f:"chaud",p:"형용사",ko:"뜨거운, 더운",en:"hot",ex:"Il fait chaud aujourd'hui.",exko:"오늘 덥네요."},
{f:"froid",p:"형용사",ko:"차가운, 추운",en:"cold",ex:"Il fait froid ce matin.",exko:"오늘 아침 춥네요."},
{f:"le café",p:"명사",ko:"커피, 카페",en:"coffee, café",ex:"Un café allongé, s'il vous plaît.",exko:"아메리카노 하나 주세요."},
{f:"le médecin",p:"명사",ko:"의사",en:"doctor",ex:"Je vais chez le médecin demain.",exko:"내일 병원에 가요."},
{f:"la gare",p:"명사",ko:"기차역",en:"train station",ex:"La gare est loin d'ici ?",exko:"기차역이 여기서 멀어요?"},
{f:"le métro",p:"명사",ko:"지하철",en:"subway",ex:"Je prends le métro tous les jours.",exko:"매일 지하철을 타요."},
{f:"le billet",p:"명사",ko:"표, 티켓",en:"ticket",ex:"Un billet pour Lyon, s'il vous plaît.",exko:"리옹행 표 한 장 주세요."},
{f:"la carte",p:"명사",ko:"카드, 메뉴, 지도",en:"card, menu, map",ex:"La carte, s'il vous plaît.",exko:"메뉴판 주세요."},
{f:"l'addition",p:"명사",ko:"계산서",en:"the bill",ex:"L'addition, s'il vous plaît.",exko:"계산서 주세요."},
{f:"gentil",p:"형용사",ko:"친절한",en:"kind, nice",ex:"Elle est très gentille.",exko:"그녀는 정말 친절해요."},
{f:"sympa",p:"형용사",ko:"좋은, 괜찮은 (구어)",en:"nice (casual)",ex:"Tes collègues ont l'air sympas.",exko:"네 동료들 좋아 보여."},
{f:"occupé",p:"형용사",ko:"바쁜",en:"busy",ex:"Je suis très occupé cette semaine.",exko:"이번 주에 아주 바빠요."},
{f:"libre",p:"형용사",ko:"한가한, 자유로운",en:"free, available",ex:"Tu es libre ce soir ?",exko:"오늘 저녁에 시간 있어?"},
{f:"la faim",p:"명사",ko:"배고픔",en:"hunger",ex:"J'ai faim !",exko:"배고파!"},
{f:"la soif",p:"명사",ko:"목마름",en:"thirst",ex:"J'ai soif.",exko:"목말라요."},
{f:"ensemble",p:"부사",ko:"함께",en:"together",ex:"On travaille ensemble.",exko:"우리는 같이 일해요."},
{f:"presque",p:"부사",ko:"거의",en:"almost",ex:"J'ai presque fini.",exko:"거의 다 끝났어요."},
{f:"enfin",p:"부사",ko:"드디어, 마침내",en:"finally",ex:"Enfin le week-end !",exko:"드디어 주말이다!"},
{f:"d'abord",p:"부사",ko:"우선, 먼저",en:"first of all",ex:"D'abord, on mange !",exko:"일단 먹자!"},
{f:"ensuite",p:"부사",ko:"그다음에",en:"then, next",ex:"Ensuite, on va au cinéma.",exko:"그다음에 영화 보러 가자."},
{f:"tôt",p:"부사",ko:"일찍",en:"early",ex:"Je me suis levé tôt.",exko:"일찍 일어났어요."},
{f:"tard",p:"부사",ko:"늦게",en:"late",ex:"Désolé, je vais arriver tard.",exko:"미안, 늦게 도착할 거야."},
{f:"tous les jours",p:"표현",ko:"매일",en:"every day",ex:"J'étudie le français tous les jours.",exko:"저는 매일 프랑스어를 공부해요."},
{f:"tout de suite",p:"표현",ko:"바로, 즉시",en:"right away",ex:"J'arrive tout de suite !",exko:"바로 갈게요!"},
/* ===== 중급 (B1) ===== */
{lv:2,f:"réussir",p:"동사",ko:"성공하다, 해내다",en:"to succeed",ex:"J'ai réussi mon entretien !",exko:"면접에 붙었어요!"},
{lv:2,f:"décider",p:"동사",ko:"결정하다",en:"to decide",ex:"On a décidé de partir plus tôt.",exko:"우리는 더 일찍 떠나기로 했어요."},
{lv:2,f:"devenir",p:"동사",ko:"~이 되다",en:"to become",ex:"C'est devenu une habitude.",exko:"그게 습관이 됐어요."},
{lv:2,f:"sembler",p:"동사",ko:"~인 것 같다",en:"to seem",ex:"Il semble fatigué aujourd'hui.",exko:"그는 오늘 피곤해 보여요."},
{lv:2,f:"croire",p:"동사",ko:"믿다, ~라고 생각하다",en:"to believe",ex:"Je crois que c'est possible.",exko:"가능하다고 생각해요."},
{lv:2,f:"espérer",p:"동사",ko:"바라다, 희망하다",en:"to hope",ex:"J'espère te voir bientôt.",exko:"곧 만나길 바라."},
{lv:2,f:"souhaiter",p:"동사",ko:"원하다, 기원하다",en:"to wish",ex:"Je te souhaite bonne chance !",exko:"행운을 빌어!"},
{lv:2,f:"accepter",p:"동사",ko:"받아들이다",en:"to accept",ex:"Elle a accepté la proposition.",exko:"그녀는 제안을 받아들였어요."},
{lv:2,f:"refuser",p:"동사",ko:"거절하다",en:"to refuse",ex:"Il a refusé de venir.",exko:"그는 오기를 거절했어요."},
{lv:2,f:"proposer",p:"동사",ko:"제안하다",en:"to propose, to suggest",ex:"Je propose qu'on fasse une pause.",exko:"잠깐 쉬는 걸 제안해요."},
{lv:2,f:"prévoir",p:"동사",ko:"예상하다, 계획하다",en:"to plan, to expect",ex:"On prévoit de la pluie demain.",exko:"내일 비가 올 예정이에요."},
{lv:2,f:"organiser",p:"동사",ko:"준비하다, 조직하다",en:"to organize",ex:"On organise une fête vendredi.",exko:"금요일에 파티를 준비하고 있어요."},
{lv:2,f:"préparer",p:"동사",ko:"준비하다",en:"to prepare",ex:"Je prépare la présentation.",exko:"발표를 준비하고 있어요."},
{lv:2,f:"utiliser",p:"동사",ko:"사용하다",en:"to use",ex:"Tu sais utiliser ce logiciel ?",exko:"이 프로그램 쓸 줄 알아?"},
{lv:2,f:"montrer",p:"동사",ko:"보여주다",en:"to show",ex:"Je te montre comment faire.",exko:"어떻게 하는지 보여줄게."},
{lv:2,f:"suivre",p:"동사",ko:"따르다, 따라가다",en:"to follow",ex:"Suivez-moi, s'il vous plaît.",exko:"저를 따라오세요."},
{lv:2,f:"rencontrer",p:"동사",ko:"만나다",en:"to meet",ex:"J'ai rencontré nos nouveaux clients.",exko:"새 고객들을 만났어요."},
{lv:2,f:"discuter",p:"동사",ko:"논의하다, 이야기하다",en:"to discuss",ex:"On en discute demain ?",exko:"내일 그거 얘기할까?"},
{lv:2,f:"raconter",p:"동사",ko:"이야기하다, 들려주다",en:"to tell (a story)",ex:"Raconte-moi ton week-end !",exko:"주말 얘기 들려줘!"},
{lv:2,f:"décrire",p:"동사",ko:"묘사하다",en:"to describe",ex:"Décrivez le problème, s'il vous plaît.",exko:"문제를 설명해주세요."},
{lv:2,f:"vérifier",p:"동사",ko:"확인하다",en:"to check, to verify",ex:"Je vérifie et je te dis.",exko:"확인하고 알려줄게."},
{lv:2,f:"corriger",p:"동사",ko:"고치다, 수정하다",en:"to correct",ex:"Tu peux corriger mon mail ?",exko:"내 메일 좀 고쳐줄래?"},
{lv:2,f:"ajouter",p:"동사",ko:"추가하다",en:"to add",ex:"J'ajoute un point à l'ordre du jour.",exko:"안건에 한 가지 추가할게요."},
{lv:2,f:"remplacer",p:"동사",ko:"교체하다, 대신하다",en:"to replace",ex:"Qui va le remplacer pendant ses congés ?",exko:"그가 휴가 간 동안 누가 대신해요?"},
{lv:2,f:"éviter",p:"동사",ko:"피하다",en:"to avoid",ex:"Évite les heures de pointe.",exko:"러시아워는 피해."},
{lv:2,f:"permettre",p:"동사",ko:"허용하다, 가능하게 하다",en:"to allow",ex:"Ça permet de gagner du temps.",exko:"그러면 시간을 절약할 수 있어요."},
{lv:2,f:"promettre",p:"동사",ko:"약속하다",en:"to promise",ex:"Je te promets d'essayer.",exko:"해보겠다고 약속할게."},
{lv:2,f:"conseiller",p:"동사",ko:"조언하다, 추천하다",en:"to advise",ex:"Je te conseille ce restaurant.",exko:"이 식당 추천해."},
{lv:2,f:"s'inquiéter",p:"동사",ko:"걱정하다",en:"to worry",ex:"Ne t'inquiète pas, ça va aller.",exko:"걱정 마, 괜찮을 거야."},
{lv:2,f:"se dépêcher",p:"동사",ko:"서두르다",en:"to hurry",ex:"Dépêche-toi, on est en retard !",exko:"서둘러, 우리 늦었어!"},
{lv:2,f:"se reposer",p:"동사",ko:"쉬다",en:"to rest",ex:"Repose-toi bien ce week-end.",exko:"주말에 푹 쉬어."},
{lv:2,f:"profiter de",p:"표현",ko:"~을 활용하다, 즐기다",en:"to take advantage of, to enjoy",ex:"Profite bien de tes vacances !",exko:"휴가 잘 즐겨!"},
{lv:2,f:"plaire",p:"동사",ko:"마음에 들다",en:"to please",ex:"Ce quartier me plaît beaucoup.",exko:"이 동네가 정말 마음에 들어요."},
{lv:2,f:"manquer",p:"동사",ko:"그립다, 부족하다",en:"to miss, to lack",ex:"Tu me manques.",exko:"네가 보고 싶어."},
{lv:2,f:"l'avis",p:"명사",ko:"의견",en:"opinion",ex:"À mon avis, c'est trop tôt.",exko:"제 생각엔 너무 일러요."},
{lv:2,f:"le conseil",p:"명사",ko:"조언",en:"advice",ex:"Merci pour ton conseil.",exko:"조언 고마워."},
{lv:2,f:"la décision",p:"명사",ko:"결정",en:"decision",ex:"C'est une bonne décision.",exko:"좋은 결정이에요."},
{lv:2,f:"le choix",p:"명사",ko:"선택",en:"choice",ex:"On n'a pas le choix.",exko:"선택의 여지가 없어요."},
{lv:2,f:"l'erreur",p:"명사",ko:"실수",en:"mistake",ex:"Tout le monde fait des erreurs.",exko:"누구나 실수를 해요."},
{lv:2,f:"la vérité",p:"명사",ko:"진실",en:"truth",ex:"Dis-moi la vérité.",exko:"진실을 말해줘."},
{lv:2,f:"l'objectif",p:"명사",ko:"목표",en:"goal, objective",ex:"Notre objectif est clair.",exko:"우리 목표는 분명해요."},
{lv:2,f:"le résultat",p:"명사",ko:"결과",en:"result",ex:"Les résultats sont très bons.",exko:"결과가 아주 좋아요."},
{lv:2,f:"l'expérience",p:"명사",ko:"경험",en:"experience",ex:"J'ai trois ans d'expérience.",exko:"3년 경력이 있어요."},
{lv:2,f:"la compétence",p:"명사",ko:"역량, 능력",en:"skill",ex:"Il a de bonnes compétences en informatique.",exko:"그는 컴퓨터 실력이 좋아요."},
{lv:2,f:"l'équipe",p:"명사",ko:"팀",en:"team",ex:"Bienvenue dans l'équipe !",exko:"팀에 온 걸 환영해!"},
{lv:2,f:"le client",p:"명사",ko:"고객",en:"client, customer",ex:"Le client n'est pas content.",exko:"고객이 만족하지 않아요."},
{lv:2,f:"le chef",p:"명사",ko:"상사, 팀장",en:"boss, chief",ex:"Mon chef est en réunion.",exko:"제 상사는 회의 중이에요."},
{lv:2,f:"le salaire",p:"명사",ko:"급여",en:"salary",ex:"Le salaire est correct.",exko:"급여는 괜찮은 편이에요."},
{lv:2,f:"le congé",p:"명사",ko:"휴가, 연차",en:"leave, day off",ex:"Je pose un congé vendredi.",exko:"금요일에 연차 낼 거예요."},
{lv:2,f:"la formation",p:"명사",ko:"교육, 연수",en:"training",ex:"Je suis une formation en français.",exko:"프랑스어 연수를 받고 있어요."},
{lv:2,f:"le début",p:"명사",ko:"시작, 초반",en:"beginning",ex:"Au début, c'était difficile.",exko:"처음엔 어려웠어요."},
{lv:2,f:"la fin",p:"명사",ko:"끝",en:"end",ex:"À la fin du mois, je déménage.",exko:"이달 말에 이사해요."},
{lv:2,f:"l'endroit",p:"명사",ko:"장소, 곳",en:"place",ex:"C'est un endroit magnifique.",exko:"정말 아름다운 곳이에요."},
{lv:2,f:"la façon",p:"명사",ko:"방법, 방식",en:"way, manner",ex:"Il y a plusieurs façons de le faire.",exko:"그걸 하는 방법은 여러 가지예요."},
{lv:2,f:"le niveau",p:"명사",ko:"수준, 레벨",en:"level",ex:"Mon niveau de français s'améliore.",exko:"제 프랑스어 실력이 늘고 있어요."},
{lv:2,f:"l'étape",p:"명사",ko:"단계",en:"step, stage",ex:"C'est la dernière étape du projet.",exko:"프로젝트의 마지막 단계예요."},
{lv:2,f:"fier",p:"형용사",ko:"자랑스러운",en:"proud",ex:"Je suis fier de toi.",exko:"네가 자랑스러워."},
{lv:2,f:"inquiet",p:"형용사",ko:"걱정하는",en:"worried",ex:"Elle est inquiète pour l'examen.",exko:"그녀는 시험 때문에 걱정하고 있어요."},
{lv:2,f:"déçu",p:"형용사",ko:"실망한",en:"disappointed",ex:"Je suis un peu déçu du résultat.",exko:"결과가 좀 실망스러워요."},
{lv:2,f:"surpris",p:"형용사",ko:"놀란",en:"surprised",ex:"J'étais surpris de le voir là.",exko:"거기서 그를 봐서 놀랐어요."},
{lv:2,f:"satisfait",p:"형용사",ko:"만족한",en:"satisfied",ex:"Vous êtes satisfait du service ?",exko:"서비스에 만족하세요?"},
{lv:2,f:"disponible",p:"형용사",ko:"시간이 되는, 이용 가능한",en:"available",ex:"Tu es disponible jeudi ?",exko:"목요일에 시간 돼?"},
{lv:2,f:"efficace",p:"형용사",ko:"효율적인, 효과적인",en:"efficient, effective",ex:"C'est une méthode très efficace.",exko:"아주 효과적인 방법이에요."},
{lv:2,f:"utile",p:"형용사",ko:"유용한",en:"useful",ex:"C'est très utile, merci !",exko:"정말 유용해요, 고마워요!"},
{lv:2,f:"pareil",p:"형용사",ko:"같은, 마찬가지인",en:"the same",ex:"C'est pareil pour moi.",exko:"나도 마찬가지야."},
{lv:2,f:"différent",p:"형용사",ko:"다른",en:"different",ex:"C'est très différent de la Corée.",exko:"한국이랑 아주 달라요."},
{lv:2,f:"plusieurs",p:"형용사",ko:"여러 개의",en:"several",ex:"J'ai plusieurs questions.",exko:"질문이 여러 개 있어요."},
{lv:2,f:"environ",p:"부사",ko:"약, 대략",en:"about, approximately",ex:"Ça prend environ une heure.",exko:"대략 한 시간 걸려요."},
{lv:2,f:"plutôt",p:"부사",ko:"오히려, 꽤",en:"rather",ex:"Je préfère plutôt le matin.",exko:"저는 오히려 아침이 좋아요."},
{lv:2,f:"pourtant",p:"부사",ko:"그런데도, 하지만",en:"yet, however",ex:"C'est simple, et pourtant ça ne marche pas.",exko:"간단한데도 작동을 안 해요."},
{lv:2,f:"d'ailleurs",p:"부사",ko:"게다가, 그러고 보니",en:"besides, by the way",ex:"D'ailleurs, tu as fini le rapport ?",exko:"그러고 보니, 보고서 다 했어?"},
{lv:2,f:"malgré",p:"전치사",ko:"~에도 불구하고",en:"despite",ex:"Malgré la pluie, on est sortis.",exko:"비가 왔는데도 우리는 나갔어요."},
{lv:2,f:"grâce à",p:"전치사",ko:"~덕분에",en:"thanks to",ex:"Grâce à toi, j'ai réussi.",exko:"네 덕분에 해냈어."},
{lv:2,f:"à cause de",p:"전치사",ko:"~때문에 (부정적)",en:"because of",ex:"Le train est en retard à cause de la neige.",exko:"눈 때문에 기차가 늦어요."},
{lv:2,f:"avoir raison",p:"표현",ko:"옳다, 맞다",en:"to be right",ex:"Tu as raison, c'est mieux comme ça.",exko:"네 말이 맞아, 그게 더 나아."},
{lv:2,f:"avoir l'air",p:"표현",ko:"~처럼 보이다",en:"to look, to seem",ex:"Tu as l'air fatigué.",exko:"너 피곤해 보여."},
/* ===== 고급·토플급 (B2-C1) ===== */
{lv:3,f:"néanmoins",p:"부사",ko:"그럼에도 불구하고",en:"nevertheless",ex:"C'est risqué ; néanmoins, ça vaut la peine.",exko:"위험하지만, 그럼에도 해볼 가치가 있어요."},
{lv:3,f:"toutefois",p:"부사",ko:"그러나, 다만",en:"however",ex:"Le plan est bon ; toutefois, il reste des questions.",exko:"계획은 좋지만, 다만 몇 가지 문제가 남아 있어요."},
{lv:3,f:"désormais",p:"부사",ko:"이제부터, 앞으로는",en:"from now on",ex:"Désormais, les réunions seront en ligne.",exko:"앞으로 회의는 온라인으로 진행돼요."},
{lv:3,f:"notamment",p:"부사",ko:"특히",en:"notably, in particular",ex:"Plusieurs pays, notamment la France, sont concernés.",exko:"여러 나라, 특히 프랑스가 해당돼요."},
{lv:3,f:"en revanche",p:"부사",ko:"반면에",en:"on the other hand",ex:"C'est cher ; en revanche, la qualité est excellente.",exko:"비싸지만, 반면에 품질은 훌륭해요."},
{lv:3,f:"par conséquent",p:"부사",ko:"그 결과, 따라서",en:"consequently",ex:"Il a plu ; par conséquent, le match est annulé.",exko:"비가 와서, 따라서 경기가 취소됐어요."},
{lv:3,f:"en outre",p:"부사",ko:"게다가, 더욱이",en:"moreover",ex:"En outre, ce projet réduit les coûts.",exko:"게다가 이 프로젝트는 비용을 줄여줘요."},
{lv:3,f:"afin de",p:"접속사",ko:"~하기 위해",en:"in order to",ex:"Afin de progresser, il faut pratiquer chaque jour.",exko:"발전하려면 매일 연습해야 해요."},
{lv:3,f:"bien que",p:"접속사",ko:"~임에도 불구하고",en:"although",ex:"Bien que ce soit difficile, je continue.",exko:"어렵긴 하지만 계속하고 있어요."},
{lv:3,f:"tandis que",p:"접속사",ko:"~인 반면",en:"whereas, while",ex:"Lui préfère la ville, tandis qu'elle aime la campagne.",exko:"그는 도시를 좋아하는 반면 그녀는 시골을 좋아해요."},
{lv:3,f:"lorsque",p:"접속사",ko:"~할 때 (문어체)",en:"when (formal)",ex:"Lorsque le projet sera fini, on fêtera ça.",exko:"프로젝트가 끝나면 축하할 거예요."},
{lv:3,f:"dès que",p:"접속사",ko:"~하자마자",en:"as soon as",ex:"Appelle-moi dès que tu arrives.",exko:"도착하자마자 전화해줘."},
{lv:3,f:"susciter",p:"동사",ko:"불러일으키다",en:"to arouse, to spark",ex:"Cette décision a suscité un débat.",exko:"이 결정은 논쟁을 불러일으켰어요."},
{lv:3,f:"entraîner",p:"동사",ko:"초래하다, 이끌다",en:"to lead to, to cause",ex:"Ce retard entraîne des coûts supplémentaires.",exko:"이 지연은 추가 비용을 초래해요."},
{lv:3,f:"engendrer",p:"동사",ko:"야기하다, 낳다",en:"to generate, to cause",ex:"Le stress engendre des problèmes de santé.",exko:"스트레스는 건강 문제를 야기해요."},
{lv:3,f:"aboutir à",p:"동사",ko:"~에 이르다, 귀결되다",en:"to lead to, to result in",ex:"Les négociations ont abouti à un accord.",exko:"협상이 합의에 이르렀어요."},
{lv:3,f:"constater",p:"동사",ko:"확인하다, 목격하다",en:"to observe, to note",ex:"On constate une nette amélioration.",exko:"뚜렷한 개선이 확인돼요."},
{lv:3,f:"souligner",p:"동사",ko:"강조하다",en:"to emphasize, to underline",ex:"Je voudrais souligner un point important.",exko:"중요한 점 하나를 강조하고 싶어요."},
{lv:3,f:"envisager",p:"동사",ko:"고려하다, 계획하다",en:"to consider, to envisage",ex:"J'envisage de changer de poste.",exko:"직무를 바꾸는 걸 고려하고 있어요."},
{lv:3,f:"considérer",p:"동사",ko:"여기다, 간주하다",en:"to consider",ex:"Je considère cela comme une priorité.",exko:"저는 그걸 우선순위로 여겨요."},
{lv:3,f:"évoquer",p:"동사",ko:"언급하다, 상기시키다",en:"to mention, to evoke",ex:"Il a évoqué ce sujet en réunion.",exko:"그가 회의에서 이 주제를 언급했어요."},
{lv:3,f:"aborder",p:"동사",ko:"(주제를) 다루다, 접근하다",en:"to tackle, to approach",ex:"Abordons maintenant la question du budget.",exko:"이제 예산 문제를 다뤄봅시다."},
{lv:3,f:"analyser",p:"동사",ko:"분석하다",en:"to analyze",ex:"Il faut analyser les données d'abord.",exko:"먼저 데이터를 분석해야 해요."},
{lv:3,f:"évaluer",p:"동사",ko:"평가하다",en:"to evaluate, to assess",ex:"On doit évaluer les risques.",exko:"위험을 평가해야 해요."},
{lv:3,f:"estimer",p:"동사",ko:"추정하다, 평가하다",en:"to estimate",ex:"J'estime le coût à dix mille euros.",exko:"비용을 만 유로로 추정해요."},
{lv:3,f:"démontrer",p:"동사",ko:"입증하다",en:"to demonstrate, to prove",ex:"Les chiffres démontrent le contraire.",exko:"수치가 그 반대를 입증해요."},
{lv:3,f:"illustrer",p:"동사",ko:"예시로 보여주다",en:"to illustrate",ex:"Cet exemple illustre bien le problème.",exko:"이 예가 문제를 잘 보여줘요."},
{lv:3,f:"refléter",p:"동사",ko:"반영하다",en:"to reflect",ex:"Ces résultats reflètent nos efforts.",exko:"이 결과는 우리의 노력을 반영해요."},
{lv:3,f:"constituer",p:"동사",ko:"구성하다, ~이 되다",en:"to constitute",ex:"Cela constitue un vrai progrès.",exko:"그것은 진정한 진전이에요."},
{lv:3,f:"comporter",p:"동사",ko:"포함하다, 수반하다",en:"to include, to involve",ex:"Ce plan comporte trois étapes.",exko:"이 계획은 세 단계로 이루어져 있어요."},
{lv:3,f:"impliquer",p:"동사",ko:"수반하다, 연루시키다",en:"to imply, to involve",ex:"Ce choix implique des sacrifices.",exko:"이 선택은 희생을 수반해요."},
{lv:3,f:"exiger",p:"동사",ko:"요구하다",en:"to demand, to require",ex:"Ce travail exige de la patience.",exko:"이 일은 인내심을 요구해요."},
{lv:3,f:"accroître",p:"동사",ko:"증가시키다",en:"to increase",ex:"L'entreprise veut accroître ses ventes.",exko:"회사는 매출을 늘리고 싶어 해요."},
{lv:3,f:"réduire",p:"동사",ko:"줄이다",en:"to reduce",ex:"Il faut réduire les dépenses.",exko:"지출을 줄여야 해요."},
{lv:3,f:"renforcer",p:"동사",ko:"강화하다",en:"to strengthen",ex:"Cela renforce notre position.",exko:"그것이 우리 입지를 강화해요."},
{lv:3,f:"favoriser",p:"동사",ko:"촉진하다, 유리하게 하다",en:"to promote, to favor",ex:"Le télétravail favorise la concentration.",exko:"재택근무는 집중에 도움이 돼요."},
{lv:3,f:"contribuer à",p:"동사",ko:"~에 기여하다",en:"to contribute to",ex:"Chacun contribue au succès de l'équipe.",exko:"모두가 팀의 성공에 기여해요."},
{lv:3,f:"il s'agit de",p:"표현",ko:"~에 관한 것이다",en:"it is about",ex:"Il s'agit d'un problème technique.",exko:"기술적인 문제에 관한 거예요."},
{lv:3,f:"se dérouler",p:"동사",ko:"진행되다, 펼쳐지다",en:"to take place, to unfold",ex:"La réunion s'est bien déroulée.",exko:"회의가 잘 진행됐어요."},
{lv:3,f:"survenir",p:"동사",ko:"(갑자기) 발생하다",en:"to occur, to arise",ex:"Un problème est survenu hier soir.",exko:"어젯밤에 문제가 발생했어요."},
{lv:3,f:"demeurer",p:"동사",ko:"여전히 ~이다, 남다",en:"to remain",ex:"La question demeure ouverte.",exko:"그 문제는 여전히 열려 있어요."},
{lv:3,f:"saisir",p:"동사",ko:"파악하다, 붙잡다",en:"to grasp, to seize",ex:"Je n'ai pas bien saisi votre idée.",exko:"당신 아이디어를 잘 이해하지 못했어요."},
{lv:3,f:"acquérir",p:"동사",ko:"습득하다, 획득하다",en:"to acquire",ex:"Elle a acquis beaucoup d'expérience ici.",exko:"그녀는 여기서 많은 경험을 쌓았어요."},
{lv:3,f:"percevoir",p:"동사",ko:"인지하다, 감지하다",en:"to perceive",ex:"Je perçois une différence subtile.",exko:"미묘한 차이가 느껴져요."},
{lv:3,f:"concevoir",p:"동사",ko:"구상하다, 설계하다",en:"to design, to conceive",ex:"Nous avons conçu un nouveau produit.",exko:"우리는 새 제품을 설계했어요."},
{lv:3,f:"élaborer",p:"동사",ko:"정교하게 만들다, 수립하다",en:"to develop, to elaborate",ex:"On élabore une nouvelle stratégie.",exko:"새 전략을 수립하고 있어요."},
{lv:3,f:"mettre en œuvre",p:"표현",ko:"실행에 옮기다",en:"to implement",ex:"Le plan sera mis en œuvre en septembre.",exko:"그 계획은 9월에 실행될 거예요."},
{lv:3,f:"remettre en question",p:"표현",ko:"재고하다, 의문을 제기하다",en:"to call into question",ex:"Il faut remettre en question nos méthodes.",exko:"우리 방식을 재고해야 해요."},
{lv:3,f:"prendre en compte",p:"표현",ko:"고려하다, 감안하다",en:"to take into account",ex:"Il faut prendre en compte tous les avis.",exko:"모든 의견을 고려해야 해요."},
{lv:3,f:"faire face à",p:"표현",ko:"직면하다, 맞서다",en:"to face, to cope with",ex:"L'équipe fait face à un grand défi.",exko:"팀이 큰 도전에 직면해 있어요."},
{lv:3,f:"l'enjeu",p:"명사",ko:"쟁점, 관건",en:"stake, issue",ex:"L'enjeu est énorme pour l'entreprise.",exko:"회사로서는 관건이 매우 커요."},
{lv:3,f:"le défi",p:"명사",ko:"도전 과제",en:"challenge",ex:"C'est un défi intéressant.",exko:"흥미로운 도전이에요."},
{lv:3,f:"la contrainte",p:"명사",ko:"제약",en:"constraint",ex:"On a des contraintes de budget.",exko:"예산 제약이 있어요."},
{lv:3,f:"l'ampleur",p:"명사",ko:"규모, 정도",en:"scale, extent",ex:"On mesure l'ampleur du problème.",exko:"문제의 규모를 가늠하고 있어요."},
{lv:3,f:"la démarche",p:"명사",ko:"접근법, 절차",en:"approach, process",ex:"J'apprécie votre démarche.",exko:"당신의 접근 방식이 좋네요."},
{lv:3,f:"le constat",p:"명사",ko:"진단, 소견",en:"observation, finding",ex:"Le constat est clair : il faut changer.",exko:"진단은 분명해요: 바꿔야 해요."},
{lv:3,f:"l'hypothèse",p:"명사",ko:"가설",en:"hypothesis",ex:"C'est une hypothèse à vérifier.",exko:"검증해야 할 가설이에요."},
{lv:3,f:"la synthèse",p:"명사",ko:"종합, 요약",en:"synthesis, summary",ex:"Je prépare une synthèse du rapport.",exko:"보고서 요약본을 준비하고 있어요."},
{lv:3,f:"le raisonnement",p:"명사",ko:"추론, 논리",en:"reasoning",ex:"Ton raisonnement est logique.",exko:"네 논리가 타당해."},
{lv:3,f:"l'efficacité",p:"명사",ko:"효율성",en:"efficiency",ex:"Il faut améliorer l'efficacité du processus.",exko:"프로세스의 효율성을 개선해야 해요."},
{lv:3,f:"la croissance",p:"명사",ko:"성장",en:"growth",ex:"La croissance est forte cette année.",exko:"올해 성장세가 강해요."},
{lv:3,f:"le développement",p:"명사",ko:"발전, 개발",en:"development",ex:"Le développement durable est essentiel.",exko:"지속 가능한 발전이 필수적이에요."},
{lv:3,f:"l'inégalité",p:"명사",ko:"불평등",en:"inequality",ex:"Les inégalités augmentent partout.",exko:"불평등이 곳곳에서 커지고 있어요."},
{lv:3,f:"l'environnement",p:"명사",ko:"환경",en:"environment",ex:"Il faut protéger l'environnement.",exko:"환경을 보호해야 해요."},
{lv:3,f:"la société",p:"명사",ko:"사회, 회사",en:"society, company",ex:"La société évolue rapidement.",exko:"사회가 빠르게 변하고 있어요."},
{lv:3,f:"le comportement",p:"명사",ko:"행동, 태도",en:"behavior",ex:"Son comportement a changé.",exko:"그의 행동이 달라졌어요."},
{lv:3,f:"la connaissance",p:"명사",ko:"지식",en:"knowledge",ex:"Il a une bonne connaissance du marché.",exko:"그는 시장을 잘 알아요."},
{lv:3,f:"pertinent",p:"형용사",ko:"적절한, 타당한",en:"relevant",ex:"C'est une remarque très pertinente.",exko:"아주 타당한 지적이에요."},
{lv:3,f:"cohérent",p:"형용사",ko:"일관된",en:"coherent, consistent",ex:"Ton argument est cohérent.",exko:"네 논거는 일관성이 있어."},
{lv:3,f:"complexe",p:"형용사",ko:"복잡한",en:"complex",ex:"La situation est plus complexe que prévu.",exko:"상황이 예상보다 복잡해요."},
{lv:3,f:"considérable",p:"형용사",ko:"상당한",en:"considerable",ex:"C'est un progrès considérable.",exko:"상당한 진전이에요."},
{lv:3,f:"significatif",p:"형용사",ko:"유의미한, 상당한",en:"significant",ex:"On observe une hausse significative.",exko:"유의미한 상승이 관찰돼요."},
{lv:3,f:"essentiel",p:"형용사",ko:"필수적인, 핵심의",en:"essential",ex:"C'est un point essentiel.",exko:"핵심적인 사항이에요."},
{lv:3,f:"indispensable",p:"형용사",ko:"없어서는 안 될",en:"indispensable",ex:"Ton aide est indispensable.",exko:"네 도움이 꼭 필요해."},
{lv:3,f:"inévitable",p:"형용사",ko:"불가피한",en:"inevitable",ex:"Le changement est inévitable.",exko:"변화는 불가피해요."},
{lv:3,f:"susceptible de",p:"표현",ko:"~할 가능성이 있는",en:"likely to",ex:"Ce plan est susceptible de changer.",exko:"이 계획은 바뀔 가능성이 있어요."},
{lv:3,f:"préalable",p:"형용사",ko:"사전의, 선행하는",en:"prior, preliminary",ex:"Une réservation préalable est nécessaire.",exko:"사전 예약이 필요해요."},
{lv:3,f:"actuel",p:"형용사",ko:"현재의",en:"current",ex:"La situation actuelle est stable.",exko:"현재 상황은 안정적이에요."},
{lv:3,f:"quotidien",p:"형용사",ko:"일상의, 매일의",en:"daily",ex:"C'est ma routine quotidienne.",exko:"제 일상 루틴이에요."},
];
